// This file is autogenerated by "go generate". Do not modify it.
// It has been generated from your 'gitlab.yaml' file.
// To update those structure, update the 'gitlab.yaml' and run 'go generate'
package main


// ************************
// Create request structure
// ************************

type ForjCommonStruct struct {
	ForjjDeploymentEnv  string `json:"deployment-env"`  // Deployment environment name
	ForjjDeploymentType string `json:"deployment-type"` // Deployment environment type
	ForjjDeployMount string `json:"forjj-deploy-mount"`
	ForjjInfra string `json:"forjj-infra"`
	ForjjInstanceName string `json:"forjj-instance-name"`
	ForjjOrganization string `json:"forjj-organization"`
	ForjjSourceMount string `json:"forjj-source-mount"`
	GitlabDebug string `json:"gitlab-debug"`
}

type CreateReq struct {
	Forj struct {
		ForjCommonStruct
	}

	Objects CreateArgReq

	Creds map[string]string
}

type CreateArgReq struct {
}

// ************************
// Update request structure
// ************************

type UpdateReq struct {
	Forj struct {
		ForjCommonStruct
	}

	Objects UpdateArgReq

	Creds map[string]string
}

type UpdateArgReq struct {
}

// **************************
// Maintain request structure
// **************************

type MaintainReq struct {
	Forj struct {
		ForjCommonStruct
		DeployTo string `json:"deploy-to"`
	}

	Objects MaintainArgReq

	Creds map[string]string
}

type MaintainArgReq struct {
}


// YamlDesc has been created from your 'gitlab.yaml' file.
const YamlDesc = "---\n" +
   "plugin: \"gitlab\"\n" +
   "version: \"0.1\"\n" +
   "description: \"gitlab plugin for FORJJ.\"\n" +
   "runtime:\n" +
   "  docker_image: \"docker.hos.hpecorp.net/forjj/gitlab\"\n" +
   "  service_type: \"REST API\"\n" +
   "  service:\n" +
   "    #socket: \"gitlab.sock\"\n" +
   "    parameters: [ \"service\", \"start\" ]\n" +
   "created_flag_file: \"{{ .InstanceName }}/forjj-{{ .Name }}.yaml\"\n" +
   "task_flags:\n" +
   "  common:\n" +
   "    forjj-infra:\n" +
   "      help: \"Name of the Infra repository to use\"\n" +
   "    gitlab-debug:\n" +
   "      help: \"To activate gitlab debug information\"\n" +
   "    forjj-source-mount: # Used by the plugin to store plugin data in yaml. See gitlab_plugin.go\n" +
   "      help: \"Where the source dir is located for gitlab plugin.\"\n" +
   "    forjj-instance-name:\n" +
   "    forjj-deploy-mount:\n" +
   "    forjj-organization:\n" +
   "  maintain:\n" +
   "    deploy-to:\n" +
   "      default: docker\n" +
   "\n" +
   "# plugin yaml documentation on https://github.com/forj-oss/goforjj/blob/master/README.md#writing-your-pluginyaml-file\n" +
   ""
